# Generated by Django 4.2.14 on 2024-08-31 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oauthqquser',
            old_name='created_at',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='oauthqquser',
            old_name='updated_at',
            new_name='update_time',
        ),
    ]
