# Generated by Django 4.2.14 on 2024-08-31 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_address_user_default_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-update_time'], 'verbose_name': '用户地址', 'verbose_name_plural': '用户地址'},
        ),
        migrations.RenameField(
            model_name='address',
            old_name='created_at',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='updated_at',
            new_name='update_time',
        ),
    ]
